-- -- 데이터베이스 생성
-- DROP DATABASE IF EXISTS `goodjob`;
-- CREATE DATABASE `goodjob` DEFAULT CHARACTER SET `utf8`;
-- USE `goodjob`;

-- 테이블 생성
DROP TABLE IF EXISTS `member`;
CREATE TABLE `member`
(
    `USERNAME` BIT(1),
    `CREATE_DATE` DATETIME(6) NOT NULL,
    `ID` BIGINT(20) PRIMARY KEY,
    `MODIFIED_DATE` DATETIME(6) NOT NULL,
    `EMAIL` VARCHAR(255),
    `NICKNAME` VARCHAR(255) UNIQUE,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `PROVIDER_TYPE` VARCHAR(255) NOT NULL
);
